# Generated by Django 5.1.15 on 2026-07-22 01:50

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("curriculum", "0002_courseweek_release_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                ("exam_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, verbose_name="시험명")),
                ("exam_date", models.DateField(verbose_name="시험일")),
                (
                    "round_no",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="회차 번호"
                    ),
                ),
                (
                    "target_grade",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="대상 학년"
                    ),
                ),
                (
                    "notice",
                    models.TextField(
                        blank=True, null=True, verbose_name="성적표 공지사항"
                    ),
                ),
                (
                    "avg_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="전체 평균",
                    ),
                ),
                (
                    "stddev",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="표준편차",
                    ),
                ),
                (
                    "max_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="최고점",
                    ),
                ),
                (
                    "top30_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="상위 30% 점수",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시각"),
                ),
            ],
            options={
                "verbose_name": "시험",
                "verbose_name_plural": "시험",
                "db_table": "exams",
            },
        ),
        migrations.CreateModel(
            name="ClassSession",
            fields=[
                ("session_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("session_date", models.DateField(verbose_name="수업일")),
                (
                    "session_no",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="차시"
                    ),
                ),
                (
                    "target_grade",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="대상 학년"
                    ),
                ),
                (
                    "memo",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="메모"
                    ),
                ),
                (
                    "course_week",
                    models.ForeignKey(
                        blank=True,
                        db_column="course_week_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="class_sessions",
                        to="curriculum.courseweek",
                        verbose_name="커리큘럼 주차",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        blank=True,
                        db_column="exam_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="class_sessions",
                        to="grades.exam",
                        verbose_name="그날 시험",
                    ),
                ),
            ],
            options={
                "verbose_name": "수업 회차",
                "verbose_name_plural": "수업 회차",
                "db_table": "class_sessions",
            },
        ),
        migrations.CreateModel(
            name="AnswerSheet",
            fields=[
                ("sheet_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "scan_image_path",
                    models.CharField(max_length=500, verbose_name="스캔 파일 경로"),
                ),
                (
                    "recognized_unique_id",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="인식된 원번"
                    ),
                ),
                (
                    "recognized_name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="인식된 이름"
                    ),
                ),
                (
                    "match_status",
                    models.CharField(
                        choices=[
                            ("정상", "정상"),
                            ("부분", "부분"),
                            ("불일치", "불일치"),
                            ("미존재", "미존재"),
                            ("중복", "중복"),
                            ("비정상", "비정상"),
                        ],
                        max_length=20,
                        verbose_name="대조 상태",
                    ),
                ),
                (
                    "is_corrected",
                    models.BooleanField(default=False, verbose_name="수동 보정 완료"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시각"),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        db_column="student_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="answer_sheets",
                        to="accounts.student",
                        verbose_name="학생",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        db_column="exam_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answer_sheets",
                        to="grades.exam",
                        verbose_name="시험",
                    ),
                ),
            ],
            options={
                "verbose_name": "OMR 답안지",
                "verbose_name_plural": "OMR 답안지",
                "db_table": "answer_sheets",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                ("question_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("q_number", models.SmallIntegerField(verbose_name="문항 번호")),
                ("answer", models.CharField(max_length=10, verbose_name="정답")),
                (
                    "points",
                    models.DecimalField(
                        decimal_places=1, max_digits=4, verbose_name="배점"
                    ),
                ),
                ("unit_major", models.CharField(max_length=50, verbose_name="대단원")),
                (
                    "unit_minor",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="중단원"
                    ),
                ),
                (
                    "wrong_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="오답률",
                    ),
                ),
                (
                    "theme_tag",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="테마"
                    ),
                ),
                (
                    "study_guide",
                    models.TextField(
                        blank=True, null=True, verbose_name="오답 학습가이드"
                    ),
                ),
                (
                    "guide_video_id",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="학습가이드 복습영상"
                    ),
                ),
                (
                    "question_format",
                    models.CharField(
                        blank=True,
                        choices=[("내신형", "내신형"), ("수능형", "수능형")],
                        max_length=10,
                        null=True,
                        verbose_name="문항 유형",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        db_column="exam_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="grades.exam",
                        verbose_name="시험",
                    ),
                ),
            ],
            options={
                "verbose_name": "문항",
                "verbose_name_plural": "문항",
                "db_table": "questions",
            },
        ),
        migrations.CreateModel(
            name="QuestionBankItem",
            fields=[
                (
                    "bank_item_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "bank_type",
                    models.CharField(
                        choices=[("내신형", "내신형"), ("수능형", "수능형")],
                        max_length=10,
                        verbose_name="은행 유형",
                    ),
                ),
                (
                    "content_path",
                    models.CharField(max_length=500, verbose_name="문제 파일 경로"),
                ),
                (
                    "answer",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="정답"
                    ),
                ),
                (
                    "unit_major",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="대단원"
                    ),
                ),
                (
                    "unit_minor",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="중단원"
                    ),
                ),
                (
                    "theme_tag",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="테마"
                    ),
                ),
                (
                    "difficulty",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="난이도"
                    ),
                ),
                (
                    "labels",
                    models.JSONField(blank=True, null=True, verbose_name="세부 라벨"),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="출처"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시각"),
                ),
            ],
            options={
                "verbose_name": "문제은행 문항",
                "verbose_name_plural": "문제은행 문항",
                "db_table": "question_bank_items",
                "indexes": [
                    models.Index(
                        condition=models.Q(("is_active", True)),
                        fields=["bank_type", "unit_major", "unit_minor"],
                        name="idx_qbank_type_unit",
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["labels"], name="idx_qbank_labels"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="QuestionSimilarMap",
            fields=[
                ("map_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "ordinal",
                    models.SmallIntegerField(
                        choices=[(1, "1번"), (2, "2번")], verbose_name="순번"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시각"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        db_column="question_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="similar_maps",
                        to="grades.question",
                        verbose_name="원 문항",
                    ),
                ),
                (
                    "similar_bank_item",
                    models.ForeignKey(
                        db_column="similar_bank_item_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="similar_maps",
                        to="grades.questionbankitem",
                        verbose_name="유사문항",
                    ),
                ),
            ],
            options={
                "verbose_name": "유사문항 매칭",
                "verbose_name_plural": "유사문항 매칭",
                "db_table": "question_similar_maps",
            },
        ),
        migrations.CreateModel(
            name="Score",
            fields=[
                ("score_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "total_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="총점",
                    ),
                ),
                (
                    "max_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="만점",
                    ),
                ),
                (
                    "percentile",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="백분위",
                    ),
                ),
                (
                    "rank_top_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="석차 상위 %",
                    ),
                ),
                (
                    "is_taken",
                    models.BooleanField(default=True, verbose_name="응시 여부"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시각"),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        db_column="exam_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="grades.exam",
                        verbose_name="시험",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        db_column="student_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scores",
                        to="accounts.student",
                        verbose_name="학생",
                    ),
                ),
            ],
            options={
                "verbose_name": "성적",
                "verbose_name_plural": "성적",
                "db_table": "scores",
            },
        ),
        migrations.CreateModel(
            name="SheetAnswer",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "marked",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="마킹 값"
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("정답", "정답"),
                            ("오답", "오답"),
                            ("무응답", "무응답"),
                            ("복수마킹", "복수마킹"),
                        ],
                        max_length=10,
                        verbose_name="채점 결과",
                    ),
                ),
                (
                    "is_corrected",
                    models.BooleanField(default=False, verbose_name="수동 보정"),
                ),
                (
                    "extra_practice_marked",
                    models.BooleanField(default=False, verbose_name="추가 마킹"),
                ),
                (
                    "extra_mark_corrected",
                    models.BooleanField(default=False, verbose_name="추가 마킹 보정"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        db_column="question_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sheet_answers",
                        to="grades.question",
                        verbose_name="문항",
                    ),
                ),
                (
                    "sheet",
                    models.ForeignKey(
                        db_column="sheet_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="grades.answersheet",
                        verbose_name="답안지",
                    ),
                ),
            ],
            options={
                "verbose_name": "문항 답안",
                "verbose_name_plural": "문항 답안",
                "db_table": "sheet_answers",
            },
        ),
        migrations.CreateModel(
            name="WeaknessCheckPdf",
            fields=[
                ("pdf_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "pdf_path",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="PDF 경로"
                    ),
                ),
                (
                    "page_count",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="페이지 수"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("생성대기", "생성대기"),
                            ("생성완료", "생성완료"),
                            ("인쇄완료", "인쇄완료"),
                            ("실패", "실패"),
                        ],
                        default="생성대기",
                        max_length=15,
                        verbose_name="상태",
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="생성 완료 시각"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시각"),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        db_column="exam_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weakness_check_pdfs",
                        to="grades.exam",
                        verbose_name="시험",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        db_column="student_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="weakness_check_pdfs",
                        to="accounts.student",
                        verbose_name="학생",
                    ),
                ),
            ],
            options={
                "verbose_name": "약점체크 PDF",
                "verbose_name_plural": "약점체크 PDF",
                "db_table": "weakness_check_pdfs",
            },
        ),
        migrations.CreateModel(
            name="WorkbookSubmission",
            fields=[
                (
                    "submission_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "image_path",
                    models.CharField(max_length=500, verbose_name="사진 경로"),
                ),
                (
                    "admin_original_text",
                    models.TextField(
                        blank=True, null=True, verbose_name="관리용 원본 텍스트"
                    ),
                ),
                (
                    "performance_grade",
                    models.CharField(
                        blank=True,
                        choices=[("A", "A"), ("B", "B"), ("C", "C")],
                        max_length=1,
                        null=True,
                        verbose_name="수행도",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="업로드 시각"),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        db_column="session_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workbook_submissions",
                        to="grades.classsession",
                        verbose_name="수업 회차",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        db_column="student_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workbook_submissions",
                        to="accounts.student",
                        verbose_name="학생",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="uploaded_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_workbook_submissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="업로드 조교",
                    ),
                ),
            ],
            options={
                "verbose_name": "워크북 제출",
                "verbose_name_plural": "워크북 제출",
                "db_table": "workbook_submissions",
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("출석", "출석"), ("결석", "결석"), ("지각", "지각")],
                        max_length=10,
                        verbose_name="출결 상태",
                    ),
                ),
                (
                    "exam_taken",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="현장 시험 응시"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="입력 시각"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="정정 시각"
                    ),
                ),
                (
                    "marked_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="marked_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="marked_attendances",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="출결 입력자",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        db_column="student_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendances",
                        to="accounts.student",
                        verbose_name="학생",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        db_column="session_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="grades.classsession",
                        verbose_name="수업 회차",
                    ),
                ),
            ],
            options={
                "verbose_name": "출결",
                "verbose_name_plural": "출결",
                "db_table": "attendances",
                "indexes": [
                    models.Index(
                        fields=["session", "status"],
                        name="idx_attendances_session_status",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("session", "student"),
                        name="uq_attendances_session_student",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("done", models.BooleanField(verbose_name="과제 수행 여부")),
                (
                    "memo",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="메모"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        db_column="student_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="accounts.student",
                        verbose_name="학생",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        db_column="session_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="grades.classsession",
                        verbose_name="수업 회차",
                    ),
                ),
            ],
            options={
                "verbose_name": "과제",
                "verbose_name_plural": "과제",
                "db_table": "assignments",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("session", "student"),
                        name="uq_assignments_session_student",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="classsession",
            index=models.Index(fields=["session_date"], name="idx_class_sessions_date"),
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.UniqueConstraint(
                fields=("exam", "q_number"), name="uq_questions_exam_q_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="questionsimilarmap",
            constraint=models.UniqueConstraint(
                fields=("question", "ordinal"), name="uq_qsm_question_ordinal"
            ),
        ),
        migrations.AddIndex(
            model_name="score",
            index=models.Index(
                fields=["student", "exam"], name="idx_scores_student_exam"
            ),
        ),
        migrations.AddConstraint(
            model_name="score",
            constraint=models.UniqueConstraint(
                fields=("exam", "student"), name="uq_scores_exam_student"
            ),
        ),
        migrations.AddIndex(
            model_name="sheetanswer",
            index=models.Index(
                condition=models.Q(
                    ("result", "오답"), ("extra_practice_marked", True), _connector="OR"
                ),
                fields=["sheet"],
                name="idx_sheet_answers_weak",
            ),
        ),
        migrations.AddConstraint(
            model_name="sheetanswer",
            constraint=models.UniqueConstraint(
                fields=("sheet", "question"), name="uq_sheet_answers_sheet_question"
            ),
        ),
        migrations.AddConstraint(
            model_name="weaknesscheckpdf",
            constraint=models.UniqueConstraint(
                fields=("exam", "student"), name="uq_weakness_pdfs_exam_student"
            ),
        ),
    ]
