# Generated by Django 5.1.15 on 2026-07-22 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="guide_video_id",
        ),
    ]
