# Generated by Django 5.1.15 on 2026-07-22 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0002_remove_question_guide_video_id"),
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="guide_video",
            field=models.ForeignKey(
                blank=True,
                db_column="guide_video_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="guided_questions",
                to="videos.video",
                verbose_name="학습가이드 복습영상",
            ),
        ),
        migrations.AddField(
            model_name="workbooksubmission",
            name="match_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("자동매칭", "자동매칭"),
                    ("수동확정", "수동확정"),
                    ("불일치", "불일치"),
                    ("인식실패", "인식실패"),
                ],
                max_length=20,
                null=True,
                verbose_name="대조 상태",
            ),
        ),
        migrations.AddField(
            model_name="workbooksubmission",
            name="recognized_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="인식된 이름"
            ),
        ),
        migrations.AddField(
            model_name="workbooksubmission",
            name="recognized_unique_id",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="인식된 원번"
            ),
        ),
    ]
