# Generated by Django 5.1.15 on 2026-07-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "grades",
            "0003_question_guide_video_workbooksubmission_match_status_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="answersheet",
            name="recognized_unique_id",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="인식된 원번"
            ),
        ),
        migrations.AlterField(
            model_name="workbooksubmission",
            name="recognized_unique_id",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="인식된 원번"
            ),
        ),
    ]
