# Generated by Django 5.1.15 on 2026-08-11 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0007_answer_sheet_scan_identity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="unit_major",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="대단원"
            ),
        ),
    ]
