# Generated by Django 5.1.15 on 2026-08-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0008_question_unit_major_optional"),
    ]

    operations = [
        migrations.AddField(
            model_name="answersheet",
            name="recognized_score",
            field=models.SmallIntegerField(
                blank=True, null=True, verbose_name="인식된 점수"
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="kind",
            field=models.CharField(
                choices=[("미니테스트", "미니테스트"), ("모의고사", "모의고사")],
                default="미니테스트",
                max_length=20,
                verbose_name="시험 종류",
            ),
        ),
    ]
