# Generated by Django 5.1.15 on 2026-08-12 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0009_answersheet_recognized_score_exam_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="answersheet",
            name="score_from_handwriting",
            field=models.BooleanField(default=False, verbose_name="손글씨에서 읽음"),
        ),
    ]
