# Generated by Django 5.1.15 on 2026-08-12 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0012_split_result_and_issue"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="full_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="만점",
            ),
        ),
    ]
