# Generated by Django 5.1.15 on 2026-08-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0013_exam_full_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="answersheet",
            name="layout_id",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="판형"
            ),
        ),
    ]
