# Generated by Django 5.1.15 on 2026-08-18 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0003_make_class_a_real_entity"),
        ("grades", "0013_exam_full_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="classsession",
            name="klass",
            field=models.ForeignKey(
                blank=True,
                db_column="class_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sessions",
                to="curriculum.class",
                verbose_name="반",
            ),
        ),
        migrations.AddField(
            model_name="classsession",
            name="week_no",
            field=models.SmallIntegerField(
                blank=True, null=True, verbose_name="주차 번호"
            ),
        ),
        migrations.AddConstraint(
            model_name="classsession",
            constraint=models.UniqueConstraint(
                fields=("klass", "week_no"), name="uq_class_sessions_class_week_no"
            ),
        ),
    ]
