# Generated by Django 5.1.15 on 2026-08-19 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0015_attendance_unentered"),
    ]

    operations = [
        migrations.AddField(
            model_name="classsession",
            name="confirmed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="출결 확정 시각"
            ),
        ),
    ]
