# Generated by Django 5.1.15 on 2026-07-21 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("course_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, verbose_name="강좌명")),
                (
                    "target_grade",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="대상 학년"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시각"),
                ),
            ],
            options={
                "verbose_name": "강좌",
                "verbose_name_plural": "강좌",
                "db_table": "courses",
            },
        ),
        migrations.CreateModel(
            name="CourseWeek",
            fields=[
                ("week_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("week_no", models.SmallIntegerField(verbose_name="주차 번호")),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="주차 제목"
                    ),
                ),
                (
                    "offline_notice",
                    models.TextField(
                        blank=True, null=True, verbose_name="오프라인 특이사항"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="시작일"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="종료일"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        db_column="course_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weeks",
                        to="curriculum.course",
                        verbose_name="강좌",
                    ),
                ),
            ],
            options={
                "verbose_name": "강좌 주차",
                "verbose_name_plural": "강좌 주차",
                "db_table": "course_weeks",
            },
        ),
        migrations.CreateModel(
            name="WeekDayPlan",
            fields=[
                ("plan_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("day_no", models.SmallIntegerField(verbose_name="Day 번호")),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="제목"
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, null=True, verbose_name="학습계획"),
                ),
                (
                    "display_order",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="표시 순서"
                    ),
                ),
                (
                    "week",
                    models.ForeignKey(
                        db_column="week_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="day_plans",
                        to="curriculum.courseweek",
                        verbose_name="주차",
                    ),
                ),
            ],
            options={
                "verbose_name": "Day 학습계획",
                "verbose_name_plural": "Day 학습계획",
                "db_table": "week_day_plans",
            },
        ),
        migrations.CreateModel(
            name="CourseEnrollment",
            fields=[
                (
                    "enrollment_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "class_name",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="반"
                    ),
                ),
                (
                    "primary_weekday",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="주 수업 요일"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("수강", "수강"), ("종료", "종료"), ("중단", "중단")],
                        default="수강",
                        max_length=15,
                        verbose_name="수강 상태",
                    ),
                ),
                (
                    "enrolled_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="수강 시작 시각"
                    ),
                ),
                (
                    "ended_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="수강 종료 시각"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        db_column="course_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrollments",
                        to="curriculum.course",
                        verbose_name="강좌",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        db_column="student_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="course_enrollments",
                        to="accounts.student",
                        verbose_name="학생",
                    ),
                ),
            ],
            options={
                "verbose_name": "수강",
                "verbose_name_plural": "수강",
                "db_table": "course_enrollments",
                "indexes": [
                    models.Index(
                        condition=models.Q(("status", "수강")),
                        fields=["student"],
                        name="idx_course_enrollments_student",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("student", "course"),
                        name="uq_course_enrollments_student_course",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="courseweek",
            constraint=models.UniqueConstraint(
                fields=("course", "week_no"), name="uq_course_weeks_course_week_no"
            ),
        ),
        migrations.AddConstraint(
            model_name="weekdayplan",
            constraint=models.UniqueConstraint(
                fields=("week", "day_no"), name="uq_week_day_plans_week_day_no"
            ),
        ),
    ]
