# Generated by Django 5.1.15 on 2026-07-22 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseweek",
            name="release_at",
            field=models.DateTimeField(
                blank=True,
                help_text="비우면 시작일 자정부터 공개. 조기 공개는 이 값을 앞당겨 설정.",
                null=True,
                verbose_name="공개 시점",
            ),
        ),
    ]
