# Generated by Django 5.1.15 on 2026-08-18 08:10

import django.db.models.deletion
from django.db import migrations, models


def backfill_classes(apps, schema_editor):
    """문자열 반 이름(`class_name`)을 `Class` 행으로 승격시킨다.

    같은 커리 안에서 같은 이름이면 한 반이다. 이름이 비어 있으면 반이
    없는 것이므로 `klass` 를 NULL 로 남긴다.
    """
    Class = apps.get_model("curriculum", "Class")
    CourseEnrollment = apps.get_model("curriculum", "CourseEnrollment")
    for enrollment in CourseEnrollment.objects.filter(klass__isnull=True).iterator():
        name = (enrollment.class_name or "").strip()
        if not name:
            continue
        klass, _ = Class.objects.get_or_create(
            course_id=enrollment.course_id, name=name
        )
        enrollment.klass = klass
        enrollment.save(update_fields=["klass"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_rename_unique_id_matching_key"),
        ("curriculum", "0002_courseweek_release_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                ("class_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, verbose_name="수강반명")),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="개강일"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시각"),
                ),
            ],
            options={
                "verbose_name": "반",
                "verbose_name_plural": "반",
                "db_table": "classes",
            },
        ),
        migrations.RemoveConstraint(
            model_name="courseenrollment",
            name="uq_course_enrollments_student_course",
        ),
        migrations.AddField(
            model_name="class",
            name="course",
            field=models.ForeignKey(
                db_column="course_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="classes",
                to="curriculum.course",
                verbose_name="커리",
            ),
        ),
        migrations.AddConstraint(
            model_name="class",
            constraint=models.UniqueConstraint(
                fields=("course", "name"), name="uq_classes_course_name"
            ),
        ),
        migrations.AddField(
            model_name="courseenrollment",
            name="klass",
            field=models.ForeignKey(
                blank=True,
                db_column="class_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="enrollments",
                to="curriculum.class",
                verbose_name="반",
            ),
        ),
        migrations.RunPython(backfill_classes, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="courseenrollment",
            constraint=models.UniqueConstraint(
                fields=("student", "klass"), name="uq_course_enrollments_student_class"
            ),
        ),
    ]
