# Generated by Django 5.1.15 on 2026-08-18 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0003_make_class_a_real_entity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="courseenrollment",
            name="class_name",
        ),
    ]
