# Generated by Django 5.1.15 on 2026-08-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0004_remove_courseenrollment_class_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="total_weeks",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="총주차"),
        ),
    ]
