# Generated by Django 5.1.15 on 2026-08-18 15:29

import django.db.models.deletion
from django.db import migrations, models

# FLOW 1-2 의 구분↔과목 표. 커리가 하나도 없어도 골라야 하는 값이라
# 시드가 아니라 마이그레이션으로 넣는다.
SUBJECTS = [
    ("수능", "통합과학"),
    ("내신", "일반선택 생명과학"),
    ("내신", "진로선택 생명과학 — 세포와 물질대사"),
    ("내신", "진로선택 생명과학 — 생물의 유전"),
]


def add_subjects(apps, schema_editor):
    Subject = apps.get_model("curriculum", "Subject")
    for track, name in SUBJECTS:
        Subject.objects.get_or_create(track=track, name=name)


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0005_course_total_weeks"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                ("subject_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "track",
                    models.CharField(
                        choices=[("수능", "수능"), ("내신", "내신")],
                        max_length=10,
                        verbose_name="과목구분",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="과목명")),
            ],
            options={
                "verbose_name": "과목",
                "verbose_name_plural": "과목",
                "db_table": "subjects",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("track", "name"), name="uq_subjects_track_name"
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="course",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                db_column="subject_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="courses",
                to="curriculum.subject",
                verbose_name="과목",
            ),
        ),
        # 역방향은 표째 사라지므로 행을 지울 것이 없다.
        migrations.RunPython(add_subjects, migrations.RunPython.noop),
    ]
