# Generated by Django 5.1.15 on 2026-08-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0006_subject_course_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="uses_payssam",
            field=models.BooleanField(default=False, verbose_name="결제선생 청구"),
        ),
    ]
