"""커리가 클리닉 시간대를 갖는다 (FLOW 1-1·3-7).

비어 있으면 그 커리는 클리닉을 안 연다 — 옛 커리는 전부 여기서 시작한다.
"""

# Generated by Django 5.1.15 on 2026-08-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0007_class_uses_payssam"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="clinic_end_time",
            field=models.TimeField(blank=True, null=True, verbose_name="클리닉 종료"),
        ),
        migrations.AddField(
            model_name="course",
            name="clinic_start_time",
            field=models.TimeField(blank=True, null=True, verbose_name="클리닉 시작"),
        ),
    ]
