# Generated by Django 5.1.15 on 2026-07-22 02:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("curriculum", "0002_courseweek_release_at"),
        ("grades", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AbsenceCounseling",
            fields=[
                ("counsel_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "target",
                    models.CharField(
                        choices=[("학부모", "학부모"), ("학생", "학생")],
                        max_length=10,
                        verbose_name="통화 대상",
                    ),
                ),
                (
                    "called_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="통화 일시"
                    ),
                ),
                (
                    "absence_reason",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="결석 사유"
                    ),
                ),
                (
                    "makeup_requested",
                    models.BooleanField(default=False, verbose_name="동보 신청 여부"),
                ),
                (
                    "call_memo",
                    models.TextField(blank=True, null=True, verbose_name="통화 내용"),
                ),
                (
                    "follow_up_action",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="후속 조치"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("대기", "대기"),
                            ("완료", "완료"),
                            ("미연결", "미연결"),
                        ],
                        default="대기",
                        max_length=15,
                        verbose_name="상태",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시각"),
                ),
                (
                    "attendance",
                    models.ForeignKey(
                        blank=True,
                        db_column="attendance_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="absence_counselings",
                        to="grades.attendance",
                        verbose_name="결석 회차",
                    ),
                ),
                (
                    "counselor",
                    models.ForeignKey(
                        blank=True,
                        db_column="counselor_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="absence_counselings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="결석 담당자",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        db_column="student_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="absence_counselings",
                        to="accounts.student",
                        verbose_name="결석생",
                    ),
                ),
            ],
            options={
                "verbose_name": "결석 상담",
                "verbose_name_plural": "결석 상담",
                "db_table": "absence_counselings",
            },
        ),
        migrations.CreateModel(
            name="ParentCounselRequest",
            fields=[
                ("request_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("request_content", models.TextField(verbose_name="상담 요청 내용")),
                (
                    "status",
                    models.CharField(
                        choices=[("접수", "접수"), ("진행", "진행"), ("완료", "완료")],
                        default="접수",
                        max_length=15,
                        verbose_name="상태",
                    ),
                ),
                (
                    "admin_reply",
                    models.TextField(
                        blank=True, null=True, verbose_name="관리자 응답 메모"
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="신청 시각"),
                ),
                (
                    "handled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="처리 시각"
                    ),
                ),
                (
                    "handled_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="handled_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="handled_counsel_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="처리자",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        db_column="parent_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="counsel_requests",
                        to="accounts.parent",
                        verbose_name="신청 학부모",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        db_column="student_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="parent_counsel_requests",
                        to="accounts.student",
                        verbose_name="대상 자녀",
                    ),
                ),
            ],
            options={
                "verbose_name": "학부모 상담 신청",
                "verbose_name_plural": "학부모 상담 신청",
                "db_table": "parent_counsel_requests",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                ("post_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("공지사항", "공지사항"),
                            ("정오표", "정오표"),
                            ("질답", "질답"),
                            ("자유게시판", "자유게시판"),
                            ("이벤트굿즈", "이벤트굿즈"),
                        ],
                        max_length=15,
                        verbose_name="카테고리",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("body", models.TextField(verbose_name="본문")),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="게시 여부"),
                ),
                (
                    "is_secret",
                    models.BooleanField(default=False, verbose_name="비밀글"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성 시각"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="수정 시각"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        db_column="author_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="posts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
                (
                    "course_week",
                    models.ForeignKey(
                        blank=True,
                        db_column="course_week_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts",
                        to="curriculum.courseweek",
                        verbose_name="주차 공지 연동",
                    ),
                ),
            ],
            options={
                "verbose_name": "게시글",
                "verbose_name_plural": "게시글",
                "db_table": "posts",
            },
        ),
        migrations.CreateModel(
            name="PostComment",
            fields=[
                ("comment_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("body", models.TextField(verbose_name="본문")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성 시각"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        db_column="author_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="post_comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        db_column="post_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="boards.post",
                        verbose_name="게시글",
                    ),
                ),
            ],
            options={
                "verbose_name": "게시글 답글",
                "verbose_name_plural": "게시글 답글",
                "db_table": "post_comments",
            },
        ),
    ]
