# Generated by Django 5.1.15 on 2026-08-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="absencecounseling",
            name="provider",
            field=models.CharField(
                blank=True,
                choices=[("채널톡", "채널톡")],
                default="",
                max_length=10,
                verbose_name="통화 경로",
            ),
        ),
        migrations.AddField(
            model_name="absencecounseling",
            name="provider_ref",
            field=models.CharField(
                blank=True, default="", max_length=64, verbose_name="통화 참조"
            ),
        ),
    ]
