# Generated by Django 5.1.15 on 2026-08-12 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0002_counseling_call_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="absencecounseling",
            name="call_transcript",
            field=models.TextField(blank=True, default="", verbose_name="통화 전사"),
        ),
    ]
