# Generated by Django 5.1.15 on 2026-08-12 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0003_counseling_transcript"),
    ]

    operations = [
        migrations.AddField(
            model_name="absencecounseling",
            name="attempts",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="통화 시도 횟수"
            ),
        ),
    ]
