# Generated by Django 5.1.15 on 2026-07-22 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("notif_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("카카오알림톡", "카카오알림톡"),
                            ("문자", "문자"),
                            ("앱푸시", "앱푸시"),
                        ],
                        max_length=15,
                        verbose_name="채널",
                    ),
                ),
                ("type", models.CharField(max_length=20, verbose_name="알림 유형")),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="제목"
                    ),
                ),
                ("body", models.TextField(blank=True, null=True, verbose_name="본문")),
                (
                    "ref_type",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="원인 유형"
                    ),
                ),
                (
                    "ref_id",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="원인 ID"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="발송 시각"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("대기", "대기"),
                            ("성공", "성공"),
                            ("실패", "실패"),
                            ("전달확인", "전달확인"),
                        ],
                        default="대기",
                        max_length=15,
                        verbose_name="상태",
                    ),
                ),
                (
                    "error_msg",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="실패 사유"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시각"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        db_column="parent_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notifications",
                        to="accounts.parent",
                        verbose_name="대상 학부모",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        db_column="student_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notifications",
                        to="accounts.student",
                        verbose_name="대상 학생",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_column="user_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="대상 직원",
                    ),
                ),
            ],
            options={
                "verbose_name": "알림",
                "verbose_name_plural": "알림",
                "db_table": "notifications",
                "indexes": [
                    models.Index(
                        condition=models.Q(("student__isnull", False)),
                        fields=["student", "-sent_at"],
                        name="idx_notif_student_sent",
                    ),
                    models.Index(
                        condition=models.Q(("parent__isnull", False)),
                        fields=["parent", "-sent_at"],
                        name="idx_notif_parent_sent",
                    ),
                    models.Index(
                        condition=models.Q(("status__in", ["대기", "실패"])),
                        fields=["status"],
                        name="idx_notif_status",
                    ),
                ],
            },
        ),
    ]
