# Generated by Django 5.1.15 on 2026-08-19 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="sent_to_phone",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="보낸 번호"
            ),
        ),
    ]
