# Generated by Django 5.1.15 on 2026-08-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_notification_sent_to_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="read_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="읽은 시각"),
        ),
    ]
