# Generated by Django 5.1.15 on 2026-07-22 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_remove_student_youtube_email_and_more"),
        ("curriculum", "0002_courseweek_release_at"),
        ("grades", "0002_remove_question_guide_video_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MakeupGrant",
            fields=[
                ("makeup_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("관리자체크", "관리자체크"),
                            ("학생신청", "학생신청"),
                            ("학부모신청", "학부모신청"),
                        ],
                        max_length=15,
                        verbose_name="신청 경로",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("신청", "신청"),
                            ("승인", "승인"),
                            ("지급완료", "지급완료"),
                            ("거절", "거절"),
                        ],
                        default="신청",
                        max_length=15,
                        verbose_name="상태",
                    ),
                ),
                (
                    "granted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="지급완료 시각"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시각"),
                ),
                (
                    "attendance",
                    models.ForeignKey(
                        blank=True,
                        db_column="attendance_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="makeup_grants",
                        to="grades.attendance",
                        verbose_name="결석 근거 회차",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="requested_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_makeup_grants",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="신청 주체",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        db_column="student_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="makeup_grants",
                        to="accounts.student",
                        verbose_name="결석 학생",
                    ),
                ),
            ],
            options={
                "verbose_name": "동보",
                "verbose_name_plural": "동보",
                "db_table": "makeup_grants",
            },
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                ("video_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                (
                    "sequence_no",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="차시"
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True,
                        choices=[("mux", "Mux"), ("vdocipher", "VdoCipher")],
                        max_length=20,
                        null=True,
                        verbose_name="호스팅 제공자",
                    ),
                ),
                (
                    "external_ref",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="외부 영상 참조 ID",
                    ),
                ),
                (
                    "duration_seconds",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="재생 길이(초)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("준비중", "준비중"),
                            ("공개", "공개"),
                            ("아카이브", "아카이브"),
                        ],
                        default="준비중",
                        max_length=15,
                        verbose_name="상태",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시각"),
                ),
                (
                    "course_week",
                    models.ForeignKey(
                        blank=True,
                        db_column="course_week_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="videos",
                        to="curriculum.courseweek",
                        verbose_name="커리큘럼 주차",
                    ),
                ),
            ],
            options={
                "verbose_name": "복습영상",
                "verbose_name_plural": "복습영상",
                "db_table": "videos",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("external_ref__isnull", False)),
                        fields=("provider", "external_ref"),
                        name="uq_videos_provider_ref",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="VideoGrant",
            fields=[
                ("grant_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("출석자동", "출석자동"),
                            ("동보", "동보"),
                            ("학생신청", "학생신청"),
                            ("수동", "수동"),
                        ],
                        max_length=15,
                        verbose_name="지급 경로",
                    ),
                ),
                ("granted_at", models.DateTimeField(verbose_name="지급 시각")),
                ("expires_at", models.DateTimeField(verbose_name="만료 예정 시각")),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="회수 시각"
                    ),
                ),
                (
                    "sync_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("대기", "대기"),
                            ("부여반영", "부여반영"),
                            ("회수반영", "회수반영"),
                            ("실패", "실패"),
                        ],
                        max_length=15,
                        null=True,
                        verbose_name="호스팅 반영 상태",
                    ),
                ),
                (
                    "synced_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="호스팅 반영 시각"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시각"),
                ),
                (
                    "attendance",
                    models.ForeignKey(
                        blank=True,
                        db_column="attendance_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="video_grants",
                        to="grades.attendance",
                        verbose_name="출석 근거",
                    ),
                ),
                (
                    "course_week",
                    models.ForeignKey(
                        db_column="course_week_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="video_grants",
                        to="curriculum.courseweek",
                        verbose_name="지급 주차",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="granted_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_video_grants",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="지급 처리자",
                    ),
                ),
                (
                    "makeup",
                    models.ForeignKey(
                        blank=True,
                        db_column="makeup_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="video_grants",
                        to="videos.makeupgrant",
                        verbose_name="동보 근거",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        db_column="student_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="video_grants",
                        to="accounts.student",
                        verbose_name="학생",
                    ),
                ),
            ],
            options={
                "verbose_name": "영상 권한",
                "verbose_name_plural": "영상 권한",
                "db_table": "video_grants",
                "indexes": [
                    models.Index(
                        fields=["student", "expires_at"],
                        name="idx_video_grants_student_exp",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("attendance__isnull", False)),
                        fields=("attendance",),
                        name="uq_video_grants_attendance",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("makeup__isnull", False)),
                        fields=("makeup",),
                        name="uq_video_grants_makeup",
                    ),
                ],
            },
        ),
    ]
