# Generated by Django 5.1.15 on 2026-08-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0003_grant_video_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="upload_ref",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="업로드 참조 ID"
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="external_ref",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="재생 참조 ID"
            ),
        ),
    ]
