# Generated by Django 5.1.15 on 2026-08-04 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_student_unique_id"),
        ("videos", "0004_video_upload_ref"),
    ]

    operations = [
        migrations.CreateModel(
            name="WatermarkTamper",
            fields=[
                ("tamper_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "occurred_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="발생 시각"),
                ),
                (
                    "student",
                    models.ForeignKey(
                        db_column="student_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="watermark_tampers",
                        to="accounts.student",
                        verbose_name="학생",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        db_column="video_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="watermark_tampers",
                        to="videos.video",
                        verbose_name="영상",
                    ),
                ),
            ],
            options={
                "verbose_name": "워터마크 제거 시도",
                "verbose_name_plural": "워터마크 제거 시도",
                "db_table": "watermark_tampers",
                "indexes": [
                    models.Index(
                        fields=["student", "-occurred_at"], name="idx_tamper_student"
                    )
                ],
            },
        ),
    ]
