# Generated by Django 5.1.15 on 2026-07-21 06:12

import apps.accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("user_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "login_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="로그인 아이디"
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        db_column="password_hash",
                        max_length=128,
                        verbose_name="password",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("대표", "대표"),
                            ("관리자", "관리자"),
                            ("조교", "조교"),
                            ("학생", "학생"),
                            ("학부모", "학부모"),
                        ],
                        max_length=10,
                        verbose_name="역할",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="이름")),
                (
                    "phone",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="연락처"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                (
                    "must_change_password",
                    models.BooleanField(
                        default=True, verbose_name="비밀번호 변경 필요"
                    ),
                ),
                (
                    "password_changed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="비밀번호 변경 시각"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시각"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "계정",
                "verbose_name_plural": "계정",
                "db_table": "users",
            },
            managers=[
                ("objects", apps.accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Parent",
            fields=[
                ("parent_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="이름"
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="연락처")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시각"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        db_column="user_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="parent",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="로그인 계정",
                    ),
                ),
            ],
            options={
                "verbose_name": "학부모",
                "verbose_name_plural": "학부모",
                "db_table": "parents",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                ("student_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "unique_id",
                    models.CharField(db_index=True, max_length=20, verbose_name="원번"),
                ),
                (
                    "grade",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="학년"
                    ),
                ),
                (
                    "school",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="학교"
                    ),
                ),
                (
                    "registered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="등록 처리 시각"
                    ),
                ),
                (
                    "noshow_count",
                    models.PositiveIntegerField(default=0, verbose_name="노쇼 누적"),
                ),
                (
                    "clinic_banned",
                    models.BooleanField(default=False, verbose_name="클리닉 이용 정지"),
                ),
                (
                    "credentials_sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="계정정보 발송 시각"
                    ),
                ),
                (
                    "current_class",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="현재 반"
                    ),
                ),
                (
                    "youtube_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="유튜브 계정",
                    ),
                ),
                (
                    "enrollment_status",
                    models.CharField(
                        choices=[
                            ("예비등록", "예비등록"),
                            ("등록", "등록"),
                            ("퇴원", "퇴원"),
                        ],
                        default="예비등록",
                        max_length=15,
                        verbose_name="등록 상태",
                    ),
                ),
                (
                    "withdrawn_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="퇴원 처리 시각"
                    ),
                ),
                (
                    "withdrawn_reason",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="퇴원 사유"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        db_column="user_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="로그인 계정",
                    ),
                ),
                (
                    "withdrawn_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="withdrawn_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="withdrawn_students",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="퇴원 처리자",
                    ),
                ),
            ],
            options={
                "verbose_name": "학생",
                "verbose_name_plural": "학생",
                "db_table": "students",
            },
        ),
        migrations.CreateModel(
            name="ParentStudent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relation",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="관계"
                    ),
                ),
                (
                    "is_primary_contact",
                    models.BooleanField(default=False, verbose_name="주 수신처"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시각"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        db_column="parent_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_students",
                        to="accounts.parent",
                        verbose_name="학부모",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        db_column="student_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_students",
                        to="accounts.student",
                        verbose_name="자녀",
                    ),
                ),
            ],
            options={
                "verbose_name": "학부모-자녀 연동",
                "verbose_name_plural": "학부모-자녀 연동",
                "db_table": "parent_students",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("parent", "student"),
                        name="uq_parent_students_parent_student",
                    )
                ],
            },
        ),
    ]
