# Generated by Django 5.1.15 on 2026-07-22 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="youtube_email",
        ),
        migrations.AddField(
            model_name="parent",
            name="credentials_sent_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="계정정보 발송 시각"
            ),
        ),
        migrations.CreateModel(
            name="StaffFeatureGrant",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "feature_key",
                    models.CharField(max_length=50, verbose_name="기능 키"),
                ),
                ("is_granted", models.BooleanField(verbose_name="부여 여부")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시각"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="변경 시각"),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="granted_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="given_feature_grants",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="부여자",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_grants",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="직원",
                    ),
                ),
            ],
            options={
                "verbose_name": "직원 기능 권한",
                "verbose_name_plural": "직원 기능 권한",
                "db_table": "staff_feature_grants",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "feature_key"),
                        name="uq_staff_feature_grants_user_key",
                    )
                ],
            },
        ),
    ]
