# Generated by Django 5.1.15 on 2026-08-05 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_student_unique_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "login_id",
                    models.CharField(max_length=50, verbose_name="로그인 아이디"),
                ),
                (
                    "ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="클라이언트 IP"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="시각"),
                ),
            ],
            options={
                "verbose_name": "로그인 실패 시도",
                "verbose_name_plural": "로그인 실패 시도",
                "db_table": "login_attempts",
                "indexes": [
                    models.Index(
                        fields=["login_id", "created_at"], name="idx_login_attempt_id"
                    ),
                    models.Index(
                        fields=["ip", "created_at"], name="idx_login_attempt_ip"
                    ),
                ],
            },
        ),
    ]
