# Generated by Django 5.1.15 on 2026-08-18 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_rename_unique_id_matching_key"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="current_class",
        ),
    ]
