# Generated by Django 5.1.15 on 2026-07-22 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("grades", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicEvalCriteria",
            fields=[
                ("criteria_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("item", models.CharField(max_length=200, verbose_name="평가 항목")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="기준 설명"
                    ),
                ),
                (
                    "display_order",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="표시 순서"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
            ],
            options={
                "verbose_name": "클리닉 평가 항목",
                "verbose_name_plural": "클리닉 평가 항목",
                "db_table": "clinic_eval_criteria",
            },
        ),
        migrations.CreateModel(
            name="ClinicRequest",
            fields=[
                ("clinic_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("requested_date", models.DateField(verbose_name="희망 날짜")),
                ("requested_time", models.TimeField(verbose_name="희망 시작 시간")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("대기", "대기"),
                            ("승인배정", "승인배정"),
                            ("미승인", "미승인"),
                            ("취소", "취소"),
                        ],
                        default="대기",
                        max_length=15,
                        verbose_name="상태",
                    ),
                ),
                (
                    "meet_url",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="구글 미트 링크",
                    ),
                ),
                (
                    "attendance_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("미처리", "미처리"),
                            ("출석", "출석"),
                            ("결석", "결석"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="클리닉 출결",
                    ),
                ),
                (
                    "attendance_marked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="출결 처리 시각"
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="취소 시각"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="신청 시각"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="시간수정 추적"
                    ),
                ),
                (
                    "assigned_staff",
                    models.ForeignKey(
                        blank=True,
                        db_column="assigned_staff_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_clinic_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="배정 조교",
                    ),
                ),
                (
                    "attendance_marked_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="attendance_marked_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="marked_clinic_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="출결 처리자",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        blank=True,
                        db_column="exam_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clinic_requests",
                        to="grades.exam",
                        verbose_name="대상 판정 근거 시험",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        db_column="student_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clinic_requests",
                        to="accounts.student",
                        verbose_name="신청 학생",
                    ),
                ),
            ],
            options={
                "verbose_name": "클리닉 신청",
                "verbose_name_plural": "클리닉 신청",
                "db_table": "clinic_requests",
            },
        ),
        migrations.CreateModel(
            name="ClinicEvaluation",
            fields=[
                ("eval_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "recording_path",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="녹음 파일 경로",
                    ),
                ),
                (
                    "ai_summary",
                    models.TextField(
                        blank=True, null=True, verbose_name="AI 녹음 요약"
                    ),
                ),
                (
                    "overall_result",
                    models.CharField(
                        blank=True,
                        choices=[("적격", "적격"), ("부적격", "부적격")],
                        max_length=10,
                        null=True,
                        verbose_name="종합 판정",
                    ),
                ),
                (
                    "needs_review",
                    models.BooleanField(default=False, verbose_name="관리자 확인 필요"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="확인 시각"
                    ),
                ),
                (
                    "review_note",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="검토 메모"
                    ),
                ),
                (
                    "evaluated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="AI 평가 시각"
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="reviewed_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_clinic_evaluations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="확인 관리자",
                    ),
                ),
                (
                    "clinic",
                    models.OneToOneField(
                        db_column="clinic_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluation",
                        to="clinic.clinicrequest",
                        verbose_name="클리닉",
                    ),
                ),
            ],
            options={
                "verbose_name": "클리닉 평가",
                "verbose_name_plural": "클리닉 평가",
                "db_table": "clinic_evaluations",
            },
        ),
        migrations.CreateModel(
            name="ClinicSlot",
            fields=[
                ("slot_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("weekday", models.SmallIntegerField(verbose_name="요일")),
                ("start_time", models.TimeField(verbose_name="시작 시간")),
                ("end_time", models.TimeField(verbose_name="종료 시간")),
                ("capacity", models.SmallIntegerField(default=1, verbose_name="정원")),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
            ],
            options={
                "verbose_name": "클리닉 슬롯",
                "verbose_name_plural": "클리닉 슬롯",
                "db_table": "clinic_slots",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("weekday", "start_time"),
                        name="uq_clinic_slots_weekday_start",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="clinicrequest",
            name="slot",
            field=models.ForeignKey(
                blank=True,
                db_column="slot_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="requests",
                to="clinic.clinicslot",
                verbose_name="신청 슬롯",
            ),
        ),
        migrations.CreateModel(
            name="ClinicEligibility",
            fields=[
                (
                    "eligibility_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "is_target",
                    models.BooleanField(default=False, verbose_name="대상자"),
                ),
                (
                    "cutoff_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="판정 기준점",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("결석", "결석"),
                            ("미응시", "미응시"),
                            ("평균이상", "평균이상"),
                        ],
                        max_length=30,
                        null=True,
                        verbose_name="미대상 사유",
                    ),
                ),
                (
                    "determined_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="판정 시각"
                    ),
                ),
                (
                    "determined_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="determined_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="determined_clinic_eligibilities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="판정자",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        db_column="exam_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clinic_eligibilities",
                        to="grades.exam",
                        verbose_name="시험",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        db_column="student_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clinic_eligibilities",
                        to="accounts.student",
                        verbose_name="학생",
                    ),
                ),
            ],
            options={
                "verbose_name": "클리닉 대상자 판정",
                "verbose_name_plural": "클리닉 대상자 판정",
                "db_table": "clinic_eligibilities",
                "indexes": [
                    models.Index(
                        condition=models.Q(("is_target", True)),
                        fields=["student"],
                        name="idx_clinic_elig_student",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("exam", "student"), name="uq_clinic_elig_exam_student"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ClinicEvaluationItem",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "result",
                    models.CharField(
                        choices=[("충족", "충족"), ("미충족", "미충족")],
                        max_length=10,
                        verbose_name="AI 판단",
                    ),
                ),
                (
                    "ai_reason",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="AI 판단 근거",
                    ),
                ),
                (
                    "admin_override",
                    models.CharField(
                        blank=True,
                        choices=[("충족", "충족"), ("미충족", "미충족")],
                        max_length=10,
                        null=True,
                        verbose_name="관리자 수정 최종값",
                    ),
                ),
                (
                    "criteria",
                    models.ForeignKey(
                        db_column="criteria_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evaluation_items",
                        to="clinic.clinicevalcriteria",
                        verbose_name="평가 항목",
                    ),
                ),
                (
                    "evaluation",
                    models.ForeignKey(
                        db_column="eval_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="clinic.clinicevaluation",
                        verbose_name="평가",
                    ),
                ),
            ],
            options={
                "verbose_name": "클리닉 평가 항목별 판단",
                "verbose_name_plural": "클리닉 평가 항목별 판단",
                "db_table": "clinic_evaluation_items",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("evaluation", "criteria"),
                        name="uq_clinic_eval_items_criteria",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="clinicrequest",
            index=models.Index(
                condition=models.Q(("status__in", ["대기", "승인배정"])),
                fields=["slot", "requested_date"],
                name="idx_clinic_req_slot",
            ),
        ),
    ]
