# Generated by Django 5.1.15 on 2026-08-12 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0004_clinic_evaluation_transcript"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicrequest",
            name="supervision_started_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="감독 시작 시각"
            ),
        ),
    ]
