# Generated by Django 5.1.15 on 2026-08-19 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0005_supervision_started_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clinicrequest",
            name="supervision_started_at",
        ),
    ]
