# Generated by Django 5.1.15 on 2026-08-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0006_drop_supervision_started_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicrequest",
            name="reject_reason",
            field=models.CharField(
                blank=True,
                choices=[("정원 마감", "정원 마감"), ("시간 불가", "시간 불가")],
                default="",
                max_length=20,
                verbose_name="미승인 사유",
            ),
        ),
    ]
