# Generated by Django 5.1.15 on 2026-07-22 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("grades", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("product_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200, verbose_name="교재명")),
                ("price", models.IntegerField(verbose_name="가격(원)")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="판매 여부"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시각"),
                ),
            ],
            options={
                "verbose_name": "교재",
                "verbose_name_plural": "교재",
                "db_table": "products",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("order_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("amount", models.IntegerField(verbose_name="청구 금액(원)")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("미결제", "미결제"),
                            ("결제완료", "결제완료"),
                            ("배부완료", "배부완료"),
                            ("취소", "취소"),
                        ],
                        default="미결제",
                        max_length=15,
                        verbose_name="상태",
                    ),
                ),
                (
                    "billed_to_phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="청구 연락처"
                    ),
                ),
                (
                    "ordered_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="청구 시각"),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="결제완료 시각"
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="배부완료 시각"
                    ),
                ),
                (
                    "is_billed",
                    models.BooleanField(default=False, verbose_name="청구서 발송 여부"),
                ),
                (
                    "billed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="청구 발송 시각"
                    ),
                ),
                (
                    "charge_trigger",
                    models.CharField(
                        blank=True,
                        choices=[("첫수업", "첫수업"), ("수동", "수동")],
                        max_length=15,
                        null=True,
                        verbose_name="청구 트리거",
                    ),
                ),
                (
                    "billed_to_parent",
                    models.ForeignKey(
                        blank=True,
                        db_column="billed_to_parent_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="billed_orders",
                        to="accounts.parent",
                        verbose_name="청구 대상 학부모",
                    ),
                ),
                (
                    "initiated_by_user",
                    models.ForeignKey(
                        blank=True,
                        db_column="initiated_by_user_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="initiated_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="결제 개시자",
                    ),
                ),
                (
                    "source_session",
                    models.ForeignKey(
                        blank=True,
                        db_column="source_session_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triggered_orders",
                        to="grades.classsession",
                        verbose_name="첫 수업 근거 회차",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        db_column="student_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="accounts.student",
                        verbose_name="구매 학생",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        db_column="product_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="payments.product",
                        verbose_name="교재",
                    ),
                ),
            ],
            options={
                "verbose_name": "주문",
                "verbose_name_plural": "주문",
                "db_table": "orders",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("payment_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "provider",
                    models.CharField(
                        choices=[("결제선생", "결제선생")],
                        max_length=20,
                        verbose_name="결제 제공자",
                    ),
                ),
                (
                    "external_ref",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="외부 결제 참조 ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("대기", "대기"),
                            ("완료", "완료"),
                            ("실패", "실패"),
                            ("취소", "취소"),
                        ],
                        max_length=15,
                        verbose_name="상태",
                    ),
                ),
                ("amount", models.IntegerField(verbose_name="결제 금액(원)")),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="결제 시각"
                    ),
                ),
                (
                    "synced_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="동기화 시각"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시각"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        db_column="order_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="payments.order",
                        verbose_name="주문",
                    ),
                ),
            ],
            options={
                "verbose_name": "결제",
                "verbose_name_plural": "결제",
                "db_table": "payments",
            },
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["status"], name="idx_orders_status"),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "취소"), _negated=True),
                fields=("student", "product"),
                name="uq_orders_active",
            ),
        ),
    ]
