# Generated by Django 5.1.15 on 2026-08-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="pay_url",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="결제 링크"
            ),
        ),
    ]
