# Generated by Django 5.1.15 on 2026-08-18 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0007_class_uses_payssam"),
        ("payments", "0002_order_pay_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="course",
            field=models.ForeignKey(
                db_column="course_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="curriculum.course",
                verbose_name="커리",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="kind",
            field=models.CharField(
                choices=[("세트", "세트"), ("낱개", "낱개")],
                default="낱개",
                max_length=10,
                verbose_name="구성",
            ),
        ),
    ]
