# Generated by Django 5.1.15 on 2026-08-20 12:23

import apps.payments.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_product_course_product_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="cover",
            field=models.FileField(
                blank=True,
                default="",
                upload_to=apps.payments.models._cover_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ("jpg", "jpeg", "png", "webp")
                    ),
                    apps.payments.models._validate_cover_size,
                ],
                verbose_name="표지 사진",
            ),
        ),
    ]
